### ISSUE TITLE
Perhaps adding more "http post requests"

### ISSUE THREAD

**Issue by marksev1** [eliseomartelli/Cancello#1]
I will now soon test your app with Node-red. I know totally 0 about android developement. Could you maybe please add more buttons on android wear so I could do more http post requests for controlling different things, the more the better :D

**Comment by marksev1** [comment]
I tried you app with Node-red and it works, awesome! So yeah please please add more buttons :).

**Comment by eliseomartelli** [comment]
Hi!

I'm planning to do an extended version of this app called "Postino" (POSTman in Italian, see the joke here...).

e-mail me here for more info: martely98@gmail.com
